name: Run Discord Steam Bot

on:
  schedule:
    - cron: '*/20 8-23 * * *'  # Runs every 15 minutes, between 08:00 and 23:59.
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
        STEAM_GROUP_URL: ${{ secrets.STEAM_GROUP_URL }}
      run: python FRT_bot.py
